import React from "react";
import { BookOpen, Brain, Target, Timer } from "lucide-react";
import { LearningCard, SpaceCard, Recommendation, StatCard, RecentChat } from "../types";

export const learningCards: LearningCard[] = [
  {
    id: 1,
    title: "Deep Work",
    author: "Cal Newport",
    progress: 68,
    gradient: "from-indigo-500 to-purple-600",
    lastSession: "2 hours ago",
    emoji: "🧠",
  },
  {
    id: 2,
    title: "Atomic Habits",
    author: "James Clear",
    progress: 42,
    gradient: "from-emerald-500 to-teal-600",
    lastSession: "Yesterday",
    emoji: "⚡",
  },
  {
    id: 3,
    title: "The Art of War",
    author: "Sun Tzu",
    progress: 91,
    gradient: "from-orange-500 to-red-600",
    lastSession: "3 days ago",
    emoji: "⚔️",
  },
  {
    id: 4,
    title: "Sapiens: A Brief History",
    author: "Yuval Noah Harari",
    progress: 15,
    gradient: "from-blue-500 to-cyan-500",
    lastSession: "1 week ago",
    emoji: "🌍",
  },
  {
    id: 5,
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    progress: 45,
    gradient: "from-pink-500 to-rose-400",
    lastSession: "Just now",
    emoji: "🤔",
  },
  {
    id: 6,
    title: "Principles",
    author: "Ray Dalio",
    progress: 8,
    gradient: "from-amber-500 to-yellow-600",
    lastSession: "2 weeks ago",
    emoji: "⚖️",
  }
];

export const spaceCards: SpaceCard[] = [
  {
    id: 1,
    title: "Deep Work by Cal Newport",
    creator: "Alex Morgan",
    conversations: 12,
    mastery: 89,
    emoji: "🧠",
    borderGradient: "from-indigo-500 to-purple-500",
    tags: ["Productivity", "Focus"],
    isActive: true,
  },
  {
    id: 2,
    title: "Atomic Habits",
    creator: "Alex Morgan",
    conversations: 8,
    mastery: 74,
    emoji: "⚡",
    borderGradient: "from-emerald-500 to-teal-500",
    tags: ["Habits", "Self-Growth"],
    isActive: true,
  },
  {
    id: 3,
    title: "The Art of War",
    creator: "Alex Morgan",
    conversations: 5,
    mastery: 95,
    emoji: "⚔️",
    borderGradient: "from-orange-500 to-red-500",
    tags: ["Strategy", "Leadership"],
    isActive: false,
  },
  {
    id: 4,
    title: "Sapiens: A Brief History",
    creator: "Alex Morgan",
    conversations: 19,
    mastery: 61,
    emoji: "🌍",
    borderGradient: "from-blue-500 to-cyan-500",
    tags: ["History", "Anthropology"],
    isActive: true,
  },
];

export const recommendations: Recommendation[] = [
  {
    id: 1,
    title: "Getting Things Done",
    author: "David Allen",
    reason: "Because you're learning productivity",
    emoji: "📋",
    gradient: "from-violet-500 to-purple-600",
    rating: 4.8,
    tags: ["Productivity", "System"],
  },
  {
    id: 2,
    title: "Flow",
    author: "Mihaly Csikszentmihalyi",
    reason: "Pairs well with Deep Work",
    emoji: "🌊",
    gradient: "from-sky-500 to-blue-600",
    rating: 4.7,
    tags: ["Psychology", "Focus"],
  },
  {
    id: 3,
    title: "Essentialism",
    author: "Greg McKeown",
    reason: "Top pick for focus learners",
    emoji: "🎯",
    gradient: "from-rose-500 to-pink-600",
    rating: 4.9,
    tags: ["Minimalism", "Self-Help"],
  },
  {
    id: 4,
    title: "Zero to One",
    author: "Peter Thiel",
    reason: "Trending in your tech circle",
    emoji: "🚀",
    gradient: "from-amber-500 to-orange-600",
    rating: 4.6,
    tags: ["Business", "Startups"],
  },
  {
    id: 5,
    title: "Thinking in Systems",
    author: "Donella Meadows",
    reason: "Because you read System Design",
    emoji: "⚙️",
    gradient: "from-teal-500 to-emerald-600",
    rating: 4.8,
    tags: ["Systems", "Science"],
  },
  {
    id: 6,
    title: "Outliers",
    author: "Malcolm Gladwell",
    reason: "Highly rated classic",
    emoji: "📈",
    gradient: "from-indigo-400 to-cyan-500",
    rating: 4.7,
    tags: ["Sociology", "Success"],
  }
];

export const statCards: StatCard[] = [
  {
    id: 1,
    label: "Hours This Week",
    value: "14.5",
    trend: "+2.3h",
    trendUp: true,
    icon: React.createElement(Timer, { size: 18 }),
    color: "text-primary",
  },
  {
    id: 2,
    label: "Active Spaces",
    value: "7",
    trend: "+2",
    trendUp: true,
    icon: React.createElement(BookOpen, { size: 18 }),
    color: "text-success",
  },
  {
    id: 3,
    label: "Questions Asked",
    value: "248",
    trend: "+31",
    trendUp: true,
    icon: React.createElement(Brain, { size: 18 }),
    color: "text-secondary",
  },
  {
    id: 4,
    label: "Mastery Score",
    value: "82%",
    trend: "+4%",
    trendUp: true,
    icon: React.createElement(Target, { size: 18 }),
    color: "text-warning",
  },
];

export const recentChats: RecentChat[] = [
  {
    id: 1,
    space: "Deep Work",
    question: "What is the difference between shallow and deep work?",
    timestamp: "2 hours ago",
    emoji: "🧠",
  },
  {
    id: 2,
    space: "Atomic Habits",
    question: "How does the habit loop work in practice?",
    timestamp: "Yesterday, 9:14 PM",
    emoji: "⚡",
  },
  {
    id: 3,
    space: "Sapiens",
    question: "Explain the cognitive revolution and its impact on humans",
    timestamp: "2 days ago",
    emoji: "🌍",
  },
  {
    id: 4,
    space: "The Art of War",
    question: "How can Sun Tzu's strategies apply to modern business?",
    timestamp: "3 days ago",
    emoji: "⚔️",
  },
];
